-- ============================================================================
-- Imports the fleet-wide supplier/technician directory from
-- technical_project_manager_suppliers_lowercase.xlsx (96 rows).
--
-- Columns map directly: supplier name -> name, contact name -> contact_name,
-- contact -> contact, phone -> phone, notes -> notes. Placeholder cells in
-- the source ("contact name", "name", "phone", "notes" - unfilled template
-- text, not real values) were left out entirely rather than imported as if
-- they were real data.
--
-- Idempotent: deletes any prior run of this exact script (matched by name)
-- before re-inserting, so it's safe to run more than once.
-- ============================================================================

delete from public.technicians where name in ('ade marine', 'aeronautica', 'alimos marina', 'amp marine', 'antonis electr.', 'athenian', 'christos carpenter', 'demos inox', 'dimitropoulos electr', 'eneq/onan', 'fp contractor', 'george carpenter', 'george diver', 'george gangways', 'ice sea', 'julian teak', 'kafetzidakis', 'kavas', 'kentro thalasis', 'lagoon', 'lalizas', 'lyrarakis linen', 'lyratzakis', 'marinos hydraulic', 'massiva wood work', 'mys tech', 'nikita gelcoat', 'nikolas carpenter', 'northstar marine', 'papanikos', 'planaco aigina', 'rope align', 'sea spirit', 'tasos electr.', 'tolis sail laundry', 'water motion', 'zafeiridis christos', 'spiros cranes', 'hellenic shipyards perama', 'nikolas drycleaning', 'aria solutions', 'chrisinox', 'kiriazis batteries', 'stamatis gelcoat', 'dimitris tank cleaning', 'active marine', 'amaltheia marine', 'ionion sails', 'nea peramos drydock', 'crew', 'shipyard', 'fisher panda generators', 'mitsos tornos', 'doyle sails', 'spanos electronics', 'rigging matters', 'kotrozos', 'riginos', 'sea and boat', 'jet engines', 'navisense', 'eco marine', 'vega', 'salacia services', 'danias marine', 'yamaha service', 'derempeis safety', 'koronakis', 'spiros bikas', 'vs yachting', 'malerdos', 'corian top', 'baltas', 'pyrsos', 'telefinos', 'sea tech', 'marinakis marine services', 'hellas marine', 'lamas pumps', 'renieris marine', 'aegean electronics', 'naveltec', 'gopure', 'spiros chains galvanize', 'servistas', 'sunreef', 'giannis marble', 'multy hull', 'cosmol', 'rouchotas', 'koligas', 'pelekanos nikitas', 'spyros zouganelis', 'nikos linens', 'marine services corfu', 'paleros lefkas');

insert into public.technicians (name, contact_name, contact, phone, notes) values
    ('ade marine', 'isidoros', null, '6942016918', 'water systems/pumps'),
    ('aeronautica', 'george fisseros', 'info@aeronautica.gr', '2109889995', 'kanvas/sails'),
    ('alimos marina', 'nasos', null, '6955698271', null),
    ('amp marine', 'antonis', null, '6976747200', 'electronic/electrician'),
    ('antonis electr.', 'antonis', null, '6972516519', null),
    ('athenian', 'sellas kostas', 'sellasko@athenian-yachts.gr', '6974484847', 'techn. manager'),
    ('christos carpenter', 'christos', null, '6972827994', 'samara'),
    ('demos inox', 'demos', null, '6937134867', null),
    ('dimitropoulos electr', 'george', null, '6972717958', null),
    ('eneq/onan', 'stefanos', 'savvasonan@tee.gr', '6944695223', 'generator mechanic'),
    ('fp contractor', null, null, null, null),
    ('george carpenter', 'george', null, '6944477789', null),
    ('george diver', 'george', null, '6974548634', 'intermare divers'),
    ('george gangways', 'george', null, '6983472626', 'wmiencch/agnaincgways /motors'),
    ('ice sea', 'giannis', null, '6936600889', 'generator mechanic'),
    ('julian teak', 'julian', null, '6945976153', null),
    ('kafetzidakis', 'maria', null, '2104137438', 'sail repairs'),
    ('kavas', 'alexandros', null, '6948305076', 'drydock alimos'),
    ('kentro thalasis', 'eleni', null, '6987917577', 'rib service/storage'),
    ('lagoon', null, null, null, null),
    ('lalizas', 'makis sales', null, '6932406986', null),
    ('lyrarakis linen', 'nikos', null, '6974307121', null),
    ('lyratzakis', 'antonis', null, '6977233161', 'mechanic'),
    ('marinos hydraulic', 'marinos', null, '6976705720', null),
    ('massiva wood work', 'kostas', null, '6936172211', 'carpenter'),
    ('mys tech', null, null, null, null),
    ('nikita gelcoat', 'nikitas', null, '6972124658', 'gelcoat'),
    ('nikolas carpenter', 'nikos', null, '6932575616', 'carpenter'),
    ('northstar marine', 'george', null, '6983836887', 'mechanic'),
    ('papanikos', null, null, null, null),
    ('planaco aigina', 'stefanos', null, '6981433845', 'drydock'),
    ('rope align', 'manolis', null, '6982867296', 'rigging'),
    ('sea spirit', 'george', null, '6985786703', 'water systems/refrigerants'),
    ('tasos electr.', 'tasos', null, '6972723117', 'electrician'),
    ('tolis sail laundry', 'panagiotis', null, '6944608710', 'sail/storage'),
    ('water motion', 'victoria', null, '6938181002', 'watersports'),
    ('zafeiridis christos', 'christos', null, '6932454864', 'water systems'),
    ('spiros cranes', 'spiros', null, '6932458286', 'crane truck'),
    ('hellenic shipyards perama', 'giannis', null, '6932358405', 'drydock'),
    ('nikolas drycleaning', 'nikolas', null, '6907005116', 'drycleaner'),
    ('aria solutions', 'harris', null, '694504920', 'refrigerant'),
    ('chrisinox', 'thanasis', null, '6977224768', null),
    ('kiriazis batteries', 'aggelos', null, '2105739000', 'e-kiriazis'),
    ('stamatis gelcoat', 'stamatis', null, '6984316421', 'gelcoat'),
    ('dimitris tank cleaning', 'dimitris', null, '6942907070', null),
    ('active marine', 'marios', null, '6980773390', 'mechanic'),
    ('amaltheia marine', 'spiros', null, null, 'electronic'),
    ('ionion sails', 'nicoleta', null, '6970926392 - 2102588985', 'lefkada managment company'),
    ('nea peramos drydock', 'giannis', null, null, null),
    ('crew', null, null, null, null),
    ('shipyard', null, null, null, null),
    ('fisher panda generators', null, null, null, null),
    ('mitsos tornos', 'dimitris', null, '6946107428', null),
    ('doyle sails', 'nikos rodousakis', null, '6987412804', null),
    ('spanos electronics', 'kostas spanos', null, '6932093051', null),
    ('rigging matters', 'george saklas', null, '6942015954', null),
    ('kotrozos', 'george', null, '6988338937', null),
    ('riginos', 'alberto', null, '6946463409', null),
    ('sea and boat', null, null, '2109735429', 'gangways'),
    ('jet engines', 'spiros', null, '6945382962', 'jet engines'),
    ('navisense', 'kozadinos giannis', null, '6972837732', 'electronics'),
    ('eco marine', 'dimitris', null, '6980507964', null),
    ('vega', 'theoxaris pappas', null, '6944261764', 'marine lights'),
    ('salacia services', 'elina kouvari', null, '6942018363', 'electronic equipment'),
    ('danias marine', 'tania kanaki', null, '2108979031', 'parking chase boats'),
    ('yamaha service', 'babis', null, '694 9768995', 'outboard engines'),
    ('derempeis safety', null, null, '2104615170', 'liferafts/ext./flares'),
    ('koronakis', null, null, null, null),
    ('spiros bikas', 'spiros', null, '693 245 8286', 'truck crane'),
    ('vs yachting', 'victoria', null, '6938181002', 'watersports'),
    ('malerdos', null, null, null, null),
    ('corian top', 'mixalis', null, '6949470647', null),
    ('baltas', 'kostas', null, '6947261072', 'truck crane'),
    ('pyrsos', null, null, null, 'safety services'),
    ('telefinos', null, null, null, 'radio communications'),
    ('sea tech', null, null, null, null),
    ('marinakis marine services', 'antonis', null, '6907953081', null),
    ('hellas marine', null, null, null, 'electronics'),
    ('lamas pumps', null, null, null, null),
    ('renieris marine', 'anastasios', null, '6932436188', 'volvo'),
    ('aegean electronics', null, null, '210 98 88 955', null),
    ('naveltec', null, null, null, 'furuno'),
    ('gopure', null, null, '00436642314111', 'water filters'),
    ('spiros chains galvanize', null, null, '6977203503', null),
    ('servistas', null, null, '2106195910', 'laundry services'),
    ('sunreef', null, null, null, null),
    ('giannis marble', null, null, '6932075970', 'marbles - corian'),
    ('multy hull', 'vasilis', null, '6977699611', null),
    ('cosmol', null, null, '2106740110', 'electrical equipment'),
    ('rouchotas', 'nikos sideris', null, '6972297993', 'parquet-deck-pergola'),
    ('koligas', null, null, '2108217184', 'woods'),
    ('pelekanos nikitas', null, null, '6988160897', 'paints-repairs-polishing'),
    ('spyros zouganelis', null, null, '693 2202571', 'sails maker'),
    ('nikos linens', null, null, '6974307121', 'bedding supplies etc'),
    ('marine services corfu', null, null, '6974435775', 'engines - generators'),
    ('paleros lefkas', null, null, null, null);
